# Generated by Django 5.1.7 on 2025-03-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synclog",
            name="id",
        ),
        migrations.AlterField(
            model_name="synclog",
            name="date",
            field=models.DateField(
                auto_now_add=True, primary_key=True, serialize=False
            ),
        ),
    ]
