# Generated by Django 5.1.7 on 2025-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0002_remove_synclog_id_alter_synclog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclog",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
