# Generated by Django 5.1.7 on 2025-03-20 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
